### PR TITLE
test: correction for 'required' definition

### PR DESCRIPTION
**Pull request by SeeSharpSoft**

### CODE REVIEW

**Comment by domoritz** [comment]
Is this file not part of a test or why do the tests pass even if you change the json only?

**Comment by SeeSharpSoft** [comment]
Yes, I suppose its not part of a test. Just stumbled across the incorrect format while re-using those definitions as test-resources for another project, and wanted to contribute in return.

**Comment by domoritz** [comment]
Thank you!

Also, are you aware of https://github.com/vega/ts-json-schema-generator?

**Comment by domoritz** [comment]
Ahh, found it. https://github.com/vega/ts-json-schema-generator/blob/master/test/valid-data-type.test.ts#L34

**Pull request merged**
