### PR TITLE
Handle const like enum with --const-as-enum option

### LINKED ISSUE #1899: Handle const like enum with only one option
Need a way to handle this problem in the generator: https://github.com/json-editor/json-editor/pull/1446

The inspiration repo implements it with optional paramater `--constAsEnum         Use enums with a single value when declaring constants.`:

https://github.com/YousefED/typescript-json-schema

### PR DESCRIPTION
**Pull request by vladimir-prisada**
Closes https://github.com/vega/ts-json-schema-generator/issues/1899

### CODE REVIEW

**Comment by arthurfiorette** [comment]
cant we settle on a default behavior that works for everyone? I dont like the approach of adding a new option just for this. Seems like trivial information that is hard to teach via documentation that if used incorrectly will lead to unexpected behavior.

**Comment by domoritz** [comment]
Yes, let's not add a config option.

**Comment by vladimir-prisada** [comment]
So, you prefer to make it as a default behavior (instead of "const" always use "enum" with single value), could it be a breaking change for current users? Probably, somebody needs to have a "const" in their schema...

**Comment by arthurfiorette** [comment]
whats the preferred way according to openapi spec?

**Comment by vladimir-prisada** [comment]
"const" keyword supported by the openapi 3.1.0 (the actual version)

Accoding to the specification, it is an equivalent to an enum with a single value:
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.1.3

**Comment by arthurfiorette** [comment]
Then why we are doing this PR in the first place? I think we should use what was specified first to increase compatibility. Everything else either by a flag or just don't implement it at all.

**Comment by domoritz** [comment]
Ups, I think I misunderstood the original issue. Yeah, let's keep the default behavior and if anyone needs enums, they can use the custom formatter from https://github.com/vega/ts-json-schema-generator/issues/1899#issuecomment-2356131944 by @vladimir-prisada. Sorry for misleading here, everyone.

**Pull request closed without merging**
