### PR TITLE
feat: don't expose types annotated as @private

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Review by domoritz — COMMENTED** [review]
How is @private different from @hidden? Should we deprecate the latter?

**Comment by jirutka** [comment]
> src/ExposeNodeParser.ts
> ##[error]  15:8  error  Delete `·`  prettier/prettier

Prettier is kinda schizophrenic – it’s forcing me `{ }` in VSCode, but ESLint’s prettier module complains about it.

**Comment by domoritz** [comment]
I integrated prettier and eslint. If you have the eslint plugin or use `yarn format`, it works.

**Comment by jirutka** [comment]
> How is @private different from @hidden? Should we deprecate the latter?

No, they are different. When you annotate a type or property as `@hidden`, it will not be included in the schema at all. `@private` just suppresses effect of the `export` keyword.

Consider the following example:

**internal.ts**:

```ts
export type ExcludeNilsExposed<T> = {
  [P in keyof T]: Exclude<T[P], undefined | null>
}

/** @private */
export type ExcludeNilsPrivate<T> = {
  [P in keyof T]: Exclude<T[P], undefined | null>
}

/** @hidden */
export type ExcludeNilsHidden<T> = {
  [P in keyof T]: Exclude<T[P], undefined | null>
}
```

**main.ts**:

```ts
import { ExcludeNilsExposed, ExcludeNilsHidden, ExcludeNilsPrivate } from './internal'

export interface MyObject {
  alpha: string
  beta?: string
  gamma: string | null
}

export type Exposed = ExcludeNilsExposed<MyObject>

export type Hidden = ExcludeNilsHidden<MyObject>

export type Private = ExcludeNilsPrivate<MyObject>
```

**Exposed**:

```json
{
  "Exposed": {
    "$ref": "#/definitions/ExcludeNilsExposed%3CSubType%3E"
  },
  "ExcludeNilsExposed<SubType>": {
    "type": "object",
    "properties": {
      "alpha": {
        "type": "string",
      },
      ...
    },
    ...
  }
}
```

**Hidden**:

```json
{}
```

It’s not included in JSON Schema at all.

**Private**:

```json
{
  "Private": {
    "type": "object",
    "properties": {
      "alpha": {
        "type": "string"
      },
      ...
    },
    ...
  }
}
```

**Comment by jirutka** [comment]
(I’ve rebased it against the current master. I forgot to pull the latest changes before.)

**Comment by domoritz** [comment]
Ahh nice. So this feature kind of addresses https://github.com/vega/ts-json-schema-generator/issues/84.

**Comment by domoritz** [comment]
At some point, we need to document `@hidden` and `@private` and some of the other annotations in the readme.

**Comment by domoritz** [comment]
At some point, we need to document `@hidden` and `@private` and some of the other annotations in the readme.

**Review by domoritz — APPROVED** [review]

**Comment by domoritz** [comment]
Note that @hidden (and probably @private) do not support properties right now.

**Comment by jirutka** [comment]
What do you mean? `@hidden` can be used on a property to exclude it from the schema. `@private` works only on a type right now.

**Comment by domoritz** [comment]
Thank you! I made a release.

**Comment by domoritz** [comment]
> @hidden can be used on a property to exclude it from the schema.

Never mind me. I misremembered. You are right!

**Pull request merged**
