### PR TITLE
Deep merge intersection properties

### PR DESCRIPTION
**Pull request by AndrewLeedham**
fixes: #115

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you and welcome to the team (I sent you an invite).

**Comment by AndrewLeedham** [comment]
> Thank you and welcome to the team (I sent you an invite).

Thanks, accepted :)

**Comment by domoritz** [comment]
This causes a bug, I think.

```
export interface Base {
    a?: "hello" | "world";
}

export interface MyInterface extends Base {
    a?: "hello";
}
```

`MyInterface` should only allow `"hello"` but the schema also allows `"world"`.

**Comment by domoritz** [comment]
Actually, it's still not correct. 

```ts
export interface Base {
    a: "hello" | "world";
}

export interface Base2 {
    a: "hello" | "typescript";
}

export type MyType = Base & Base2;

const a: MyType = {
    a: "world",
};
```

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyType": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "enum": [
            "hello",
            "typescript",
            "world"
          ],
          "type": "string"
        }
      },
      "required": [
        "a"
      ],
      "type": "object"
    }
  }
}
```

**Pull request merged**
