### PR TITLE
chore: release

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
@hydrosquall us there something specific I should do besides making a pull request and then merging it? Should I rebase release prs?

**Comment by hydrosquall** [comment]
@domoritz I don't think rebases will be needed, given that `next` is the source of truth, and that we aren't merging any changes into `stable` that didn't go through `next` first.

**Comment by domoritz** [comment]
Normal merge adds a merge commit, no (no fast forward is the default, https://git-scm.com/docs/git-merge#_fast_forward_merge)? 

Alternatively, I can also just merge the changes into stable locally and push them.

Did you see my issue with the dependency updates ending up in the wrong category in https://github.com/vega/ts-json-schema-generator/releases/tag/v0.95.0?

**Comment by hydrosquall** [comment]
Ah when I said there’s nothing new, I just meant there aren't any feature
commits being merged into stable directly. There’s no need to backport the
merge commits from stable into “next”.

Re: wrong category - I think this might be because of how the dependency
updates are merged into “next” differently from the human prs. Note that
they’re all associated with this PR, 872. Given that those changes were
made with rebases, i think the commit hash  the inside the bot PRs don’t
match what’s in next, so it couldn’t find a matching PR and defaulted to
the current. I think that’s  why the pr # for all but #863 is the release
PR.

To fix this, we could either start using merge commits for bots, or file a
feature request / bug report in the main auto repo to see if this is the
intended behavior for rebase based merges.

**Comment by domoritz** [comment]
I would prefer to keep a linear history. I would be okay with squash merge or rebase for dependabot prs.

**Comment by hydrosquall** [comment]
Let’s try squash merges for the next batch of dependabots, and see if
that works.

**Comment by domoritz** [comment]
Why doens't auto look at the commit message? Does every commit need to be associated with a pull request because sometimes it may not (e.g. when I push stuff directly to next).

**Comment by hydrosquall** [comment]
> Why doesn't auto look at the commit message?

I think auto looks at commit message to decide what type of bump (minor, major, patch) to apply, but it uses the PR titles to make the CHANGELOG [docs](https://intuit.github.io/auto/docs/generated/changelog) (which is why each commit has a link to a PR # next to it). 

> Does every commit need to be associated with a pull request,  

For the purposes of the changelog, I think so, but the specific changelog content could be customized. https://intuit.github.io/auto/docs/plugins/changelog-hooks . My current theory is if if they're not associated with a pull request, they just won't show up.

> (e.g. when I push stuff directly to next).

I think it's discouraged to push directly to a pre-release branch ( https://intuit.github.io/auto/docs/generated/next#setting-up-protected-branches ), but I haven't personally experienced what exactly specifically would break if we did that (maybe just the changelog generation part). Perhaps @hipstersmoothie or @zephraph may know (I'll ask in the repo).

**Comment by domoritz** [comment]
I switched to squash so hopefully that fixes it next time: https://github.com/vega/ts-json-schema-generator/commit/2005b30630c1db376eaf194c3933925899682ccb.

**Pull request merged**
