### PR TITLE
test: add correct schema to test

### PR DESCRIPTION
**Pull request by SeeSharpSoft**

### CODE REVIEW

**Comment by domoritz** [comment]
1s slower than me ;-) #710

**Comment by SeeSharpSoft** [comment]
mmhh, this is 709, so... 🥈 for you I guess?! 😄

**Comment by domoritz** [comment]
Okay, here is your 🥇.

**Comment by SeeSharpSoft** [comment]
Thanks! 🤣 And great project btw! I noticed the predecessor project, but seeing this setup & implementation is a beauty! 👏

**Comment by domoritz** [comment]
Thank you. WEe heavily rely on it for https://github.com/vega/vega-lite so I had to make it work for a very large TS project.

**Pull request merged**
