### PR TITLE
Adds support for nested generics

### PR DESCRIPTION
**Pull request by robertdempsey**
Adds support for the following:

`export interface MyObject extends Partial<IRequestParams<IRes>> { }`

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you!

**Comment by robertdempsey** [comment]
No, thank you!

**Comment by robertdempsey** [comment]
@domoritz, what's the process for getting a new version published to npm?

**Comment by domoritz** [comment]
I'll make a release but I need to fix some issue I see in vega-lite.

**Comment by robertdempsey** [comment]
Okay. Cool. Thanks a lot.

**Pull request merged**
