### PR TITLE
Class support

### PR DESCRIPTION
**Pull request by kayahr**
This PR implements class support. Classes are handled like interfaces so the parser implementation is just a slightly modified copy of the interface node parser.

All class properties are processed, even protected and private. Not sure if this makes sense but I kept it that way because the typescript-json-schema tool also did this.

### CODE REVIEW

**Comment by domoritz** [comment]
If the class and interface parser are so similar, should we merge them?

I think hiding private and protected properties makes more sense since they are not part of the public interface.

**Comment by kayahr** [comment]
Ok, going to hide private and protected then.

Regarding merging interface and class node parser... Instead of creating an abstract base class containing the common stuff and deriving the two parsers from it it would be a lot easier to simply have one class which handles both node types. Only need to change some types to union types and add a few conditionals. But I'm not sure how to name the class then. Is "InterfaceAndClassNodeParser" find with you?

**Comment by domoritz** [comment]
> it would be a lot easier to simply have one class which handles both node types.

That's what I was having in mind. `InterfaceAndClassNodeParser` sounds good.

**Comment by domoritz** [comment]
Thank you!

**Pull request merged**
