### PR TITLE
chore: assertValidSchema should take config as argument

### PR DESCRIPTION
**Pull request by mdesousa**

### CODE REVIEW

**Comment by mdesousa** [comment]
@domoritz here's the PR to pass the config object to `assertValidSchema`

**Review by domoritz — CHANGES_REQUESTED** [review]
Thanks! Let's make `type` a normal argument of the method since it's always required.

**Comment by mdesousa** [comment]
yeah I noticed that @domoritz , but since the type is a property of the ‘Config’ object it seemed to make sense to move it into the config argument. since type is optional in the config, it means that tests can also be written without a type. are you sure that you want to break it out into its own argument?

**Comment by domoritz** [comment]
We could still allow type with undefined later. I think it'll make the call sites cleaner.

**Comment by mdesousa** [comment]
ok @domoritz see the latest update... it does look cleaner :)

**Comment by domoritz** [comment]
Thank you

**Pull request merged**
