### PR TITLE
chore: switch yarn to npm

### PR DESCRIPTION
**Pull request by domoritz**
<details>
  <summary>📦 Published PR as canary version: <code>2.3.1--canary.2131.2f5e0d3.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install ts-json-schema-generator@2.3.1--canary.2131.2f5e0d3.0
  # or 
  yarn add ts-json-schema-generator@2.3.1--canary.2131.2f5e0d3.0
  ```
</details>

### CODE REVIEW

**Comment by arthurfiorette** [comment]
`pnpm` would be a good move instead of `npm`... faster installs, faster ci, [`shell-emulator`](https://github.com/pnpm/pnpm.io/issues/485)

**Comment by domoritz** [comment]
But another thing to install besides node. I'll move to npm for now and maybe at some point we can consider pnpm for all of the Vega projects. I want to be consistent, though.

**Comment by domoritz** [comment]
Moving ahead since npm install is 20s which is way faster than the 6m for tests. moving away from yarn is important since many people get confused that they need to install an old version (v1) of yarn. 

Screenshot 2024-12-11 at 00 22 59

**Comment by arthurfiorette** [comment]
makes sense! good decision :)

**Pull request merged**
